# CMake generated Testfile for 
# Source directory: /src/tests
# Build directory: /src/obj-x86_64-linux-gnu/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(utilities_test "/src/obj-x86_64-linux-gnu/tests/utilities_test")
set_tests_properties(utilities_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;101;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(concurrentrun_test "/src/obj-x86_64-linux-gnu/tests/concurrentrun_test")
set_tests_properties(concurrentrun_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;102;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(mergedproxymodel_test "/src/obj-x86_64-linux-gnu/tests/mergedproxymodel_test")
set_tests_properties(mergedproxymodel_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;103;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(sqlite_test "/src/obj-x86_64-linux-gnu/tests/sqlite_test")
set_tests_properties(sqlite_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;104;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(tagreader_test "/src/obj-x86_64-linux-gnu/tests/tagreader_test")
set_tests_properties(tagreader_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;105;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(collectionbackend_test "/src/obj-x86_64-linux-gnu/tests/collectionbackend_test")
set_tests_properties(collectionbackend_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;106;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(collectionmodel_test "/src/obj-x86_64-linux-gnu/tests/collectionmodel_test")
set_tests_properties(collectionmodel_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;107;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(songplaylistitem_test "/src/obj-x86_64-linux-gnu/tests/songplaylistitem_test")
set_tests_properties(songplaylistitem_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;108;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(m3uparser_test "/src/obj-x86_64-linux-gnu/tests/m3uparser_test")
set_tests_properties(m3uparser_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;109;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(organizeformat_test "/src/obj-x86_64-linux-gnu/tests/organizeformat_test")
set_tests_properties(organizeformat_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;110;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(smartplaylistsearch_test "/src/obj-x86_64-linux-gnu/tests/smartplaylistsearch_test")
set_tests_properties(smartplaylistsearch_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;111;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(playlist_test "/src/obj-x86_64-linux-gnu/tests/playlist_test")
set_tests_properties(playlist_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;112;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(subsonicplaylistrequest_test "/src/obj-x86_64-linux-gnu/tests/subsonicplaylistrequest_test")
set_tests_properties(subsonicplaylistrequest_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;127;add_test;/src/tests/CMakeLists.txt;0;")
add_test(waveformbuilder_test "/src/obj-x86_64-linux-gnu/tests/waveformbuilder_test")
set_tests_properties(waveformbuilder_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;130;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(waveformpipeline_test "/src/obj-x86_64-linux-gnu/tests/waveformpipeline_test")
set_tests_properties(waveformpipeline_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;131;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(waveformloader_test "/src/obj-x86_64-linux-gnu/tests/waveformloader_test")
set_tests_properties(waveformloader_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;132;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(waveformcontroller_test "/src/obj-x86_64-linux-gnu/tests/waveformcontroller_test")
set_tests_properties(waveformcontroller_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;133;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(waveformrenderer_test "/src/obj-x86_64-linux-gnu/tests/waveformrenderer_test")
set_tests_properties(waveformrenderer_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;134;add_test_file;/src/tests/CMakeLists.txt;0;")
add_test(waveformproxystyle_test "/src/obj-x86_64-linux-gnu/tests/waveformproxystyle_test")
set_tests_properties(waveformproxystyle_test PROPERTIES  _BACKTRACE_TRIPLES "/src/tests/CMakeLists.txt;96;add_test;/src/tests/CMakeLists.txt;135;add_test_file;/src/tests/CMakeLists.txt;0;")
