/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p kglobalaccelcomponent /src/src/globalshortcuts/org.kde.KGlobalAccel.Component.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef KGLOBALACCELCOMPONENT_H
#define KGLOBALACCELCOMPONENT_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.kde.kglobalaccel.Component
 */
class OrgKdeKglobalaccelComponentInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.kglobalaccel.Component"; }

public:
    OrgKdeKglobalaccelComponentInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgKdeKglobalaccelComponentInterface();

    Q_PROPERTY(QString friendlyName READ friendlyName)
    inline QString friendlyName() const
    { return qvariant_cast< QString >(property("friendlyName")); }

    Q_PROPERTY(QString uniqueName READ uniqueName)
    inline QString uniqueName() const
    { return qvariant_cast< QString >(property("uniqueName")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<bool> cleanUp()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("cleanUp"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getShortcutContexts()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getShortcutContexts"), argumentList);
    }

    inline QDBusPendingReply<> invokeShortcut(const QString &actionName)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(actionName);
        return asyncCallWithArgumentList(QStringLiteral("invokeShortcut"), argumentList);
    }

    inline QDBusPendingReply<bool> isActive()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("isActive"), argumentList);
    }

    inline QDBusPendingReply<QStringList> shortcutNames()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("shortcutNames"), argumentList);
    }

    inline QDBusPendingReply<QStringList> shortcutNames(const QString &context)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(context);
        return asyncCallWithArgumentList(QStringLiteral("shortcutNames"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void globalShortcutPressed(const QString &componentUnique, const QString &actionUnique, qlonglong timestamp);
    void globalShortcutRepeated(const QString &componentUnique, const QString &actionUnique, qlonglong timestamp);
};

namespace org {
  namespace kde {
    namespace kglobalaccel {
      using Component = ::OrgKdeKglobalaccelComponentInterface;
    }
  }
}
#endif
