/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p kglobalaccel /src/src/globalshortcuts/org.kde.KGlobalAccel.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "kglobalaccel.h"

/*
 * Implementation of interface class OrgKdeKGlobalAccelInterface
 */

OrgKdeKGlobalAccelInterface::OrgKdeKGlobalAccelInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeKGlobalAccelInterface::~OrgKdeKGlobalAccelInterface()
{
}


#include "kglobalaccel.moc"
