/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -m -i includes/dbus_metatypes.h -p udisks2job /src/src/device/org.freedesktop.UDisks2.Job.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "udisks2job.h"

/*
 * Implementation of interface class OrgFreedesktopUDisks2JobInterface
 */

OrgFreedesktopUDisks2JobInterface::OrgFreedesktopUDisks2JobInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopUDisks2JobInterface::~OrgFreedesktopUDisks2JobInterface()
{
}


#include "udisks2job.moc"
