#ifndef APICREDENTIALS_H_IN
#define APICREDENTIALS_H_IN

/* #undef API_CREDENTIALS_ENCRYPTION_KEY */

/* #undef ACOUSTID_API_KEY */

/* #undef LASTFM_API_KEY */
/* #undef LASTFM_SHARED_SECRET */

/* #undef LISTENBRAINZ_CLIENT_ID */
/* #undef LISTENBRAINZ_CLIENT_SECRET */

/* #undef OPENTIDAL_CLIENT_ID */
/* #undef OPENTIDAL_CLIENT_SECRET */

/* #undef SPOTIFY_CLIENT_ID */
/* #undef SPOTIFY_CLIENT_SECRET */

/* #undef GENIUS_CLIENT_ID */
/* #undef GENIUS_CLIENT_SECRET */

/* #undef MUSIXMATCH_APP_ID */
/* #undef MUSIXMATCH_APP_SECRET */

/* #undef DISCOGS_CLIENT_ID */
/* #undef DISCOGS_CLIENT_SECRET */

/* #undef TIDAL_CLIENT_ID */

#endif  // APICREDENTIALS_H_IN
