/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -m -i includes/dbus_metatypes.h -p udisks2block /src/src/device/org.freedesktop.UDisks2.Block.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "udisks2block.h"

/*
 * Implementation of interface class OrgFreedesktopUDisks2BlockInterface
 */

OrgFreedesktopUDisks2BlockInterface::OrgFreedesktopUDisks2BlockInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopUDisks2BlockInterface::~OrgFreedesktopUDisks2BlockInterface()
{
}


#include "udisks2block.moc"
